PATH=$PATH:/usr/lib:~/bin/cygwin

export MINGW_PATH='/usr/i686-pc-mingw32/sys-root/mingw'

pathadd=.:${MINGW_PATH}/bin

gomin()
{
  export CC='i686-pc-mingw32-gcc'
  export PATH=$pathadd:$PATH
  export PS1='\[\e[32m\]MINGW\[\e[m\] \W $ '
  alias configure="./configure --prefix=$MINGW_PATH"
}

gocyg()
{
  export PATH=${PATH/$pathadd}

  export CC='gcc'
  export PS1='\W $ '
  alias configure="./configure"
}

gocyg
