PATH=$PATH:/usr/lib:~/bin/cygwin

export MINGW_PATH='/usr/i686-pc-mingw32/sys-root/mingw'

gomin()
{
  export CC='i686-pc-mingw32-gcc'
  # when change this line, change in gocyg() accordingly
  export PATH=.:${MINGW_PATH}/bin:$PATH
  export PS1='\[\e[32m\]MINGW\[\e[m\] \W $ '
  alias configure="./configure --prefix=$MINGW_PATH"
}

gocyg()
{
  PATH1=${PATH/.}
  export PATH=${PATH1/${MINGW_PATH}\/bin}
  export CC='gcc'
  export PS1='\W $ '
  alias configure="./configure"
}

gocyg
